SET SCHEMA PAY_TEST;
INSERT INTO PAY_TEST_CASE (ENTITY_CODE, ORIGIN_CODE, PAY_SUB_TYPE_ID,TEST_CASE_NAME,TEST_CASE_DESCPRIPTION) VALUES 
('14024', 'SWIFTNET', 
(SELECT PAY_SUB_TYPE_ID FROM PAY_SUB_TYPE WHERE PAY_SUB_TYPE_CODE = 'OL2F'),
'INCREDITACC',
'TEST INVALID CREDIT ACCOUNT'
);